/*
 * SongScribe song notation program
 * Copyright (C) Sri Chinmoy Centres International
 *
 * This file is part of SongScribe.
 *
 * SongScribe is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * SongScribe is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package songscribe.ui.component;

import java.awt.Dimension;
import java.awt.Insets;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JSpinner;
import javax.swing.event.ChangeListener;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import org.jspecify.annotations.Nullable;

import songscribe.Strings;

@SuppressWarnings("NonStaticInitializer")
public class BorderPanel extends JPanel {

    @SuppressWarnings("NullAway.Init")
    private JPanel expertBorderPanel;

    @SuppressWarnings("NullAway.Init")
    private JSpinner topSpinner;

    @SuppressWarnings("NullAway.Init")
    private JSpinner leftSpinner;

    @SuppressWarnings("NullAway.Init")
    private JSpinner bottomSpinner;

    @SuppressWarnings("NullAway.Init")
    private JSpinner rightSpinner;

    @SuppressWarnings("NullAway.Init")
    private JButton expertBorderButton;

    @SuppressWarnings("NullAway.Init")
    private JPanel simpleBorderPanel;

    @SuppressWarnings("NullAway.Init")
    private JSpinner borderSpinner;

    @SuppressWarnings("NullAway.Init")
    private JPanel borderPanel;

    /** Default border size (in pixels) applied to the uniform spinner on construction. Package-private for testing. */
    static final int DEFAULT_BORDER_SIZE = 10;

    private boolean exportBorder = false;
    private @Nullable ActionListener packListener = null;

    public BorderPanel() {
        borderSpinner.setValue(DEFAULT_BORDER_SIZE);
        expertBorderButton.addActionListener(_ -> {
            setExpertBorder(!exportBorder);

            if (packListener != null) {
                packListener.actionPerformed(null);
            }
        });
        add(borderPanel);
    }

    public void setPackListener(ActionListener packListener) {
        this.packListener = packListener;
    }

    public void addChangeListener(ChangeListener changeListener) {
        borderSpinner.addChangeListener(changeListener);
        topSpinner.addChangeListener(changeListener);
        leftSpinner.addChangeListener(changeListener);
        bottomSpinner.addChangeListener(changeListener);
        rightSpinner.addChangeListener(changeListener);
    }

    public void setExpertBorder(boolean expert) {
        exportBorder = expert;
        expertBorderButton.setText(expert ? Strings.get(Strings.LABEL_BORDER_SIMPLE) : Strings.get(Strings.LABEL_BORDER_EXPERT));
        expertBorderPanel.setVisible(expert);
        simpleBorderPanel.setVisible(!expert);

        if (expert) {
            topSpinner.setValue(borderSpinner.getValue());
            leftSpinner.setValue(borderSpinner.getValue());
            bottomSpinner.setValue(borderSpinner.getValue());
            rightSpinner.setValue(borderSpinner.getValue());
        }
    }

    public MyBorder getMyBorder() {
        return !exportBorder
            ? new MyBorder((Integer) borderSpinner.getValue())
            : new MyBorder(
                (Integer) topSpinner.getValue(),
                (Integer) bottomSpinner.getValue(),
                (Integer) leftSpinner.getValue(),
                (Integer) rightSpinner.getValue()
            );
    }

    /** Sets the uniform border spinner value. Package-private for testing. */
    void setUniformBorderValue(int value) {
        borderSpinner.setValue(value);
    }

    /** Sets the four edge spinner values directly. Package-private for testing. */
    void setEdgeBorderValues(int top, int bottom, int left, int right) {
        topSpinner.setValue(top);
        bottomSpinner.setValue(bottom);
        leftSpinner.setValue(left);
        rightSpinner.setValue(right);
    }

    {
        // GUI initializer generated by IntelliJ IDEA GUI Designer
        // >>> IMPORTANT!! <<<
        // DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        borderPanel = new JPanel();
        borderPanel.setLayout(
            new GridLayoutManager(2, 5, new Insets(0, 0, 0, 0), -1, -1)
        );
        final JLabel label1 = new JLabel();
        label1.setText(Strings.get(Strings.LABEL_BORDER));
        borderPanel.add(
            label1,
            new GridConstraints(
                0,
                0,
                1,
                1,
                GridConstraints.ANCHOR_WEST,
                GridConstraints.FILL_NONE,
                GridConstraints.SIZEPOLICY_FIXED,
                GridConstraints.SIZEPOLICY_FIXED,
                null,
                null,
                null,
                0,
                false
            )
        );
        simpleBorderPanel = new JPanel();
        simpleBorderPanel.setLayout(
            new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1)
        );
        borderPanel.add(
            simpleBorderPanel,
            new GridConstraints(
                0,
                1,
                1,
                1,
                GridConstraints.ANCHOR_CENTER,
                GridConstraints.FILL_BOTH,
                GridConstraints.SIZEPOLICY_CAN_SHRINK |
                GridConstraints.SIZEPOLICY_CAN_GROW,
                GridConstraints.SIZEPOLICY_CAN_SHRINK |
                GridConstraints.SIZEPOLICY_CAN_GROW,
                null,
                null,
                null,
                0,
                false
            )
        );
        borderSpinner = new JSpinner();
        simpleBorderPanel.add(
            borderSpinner,
            new GridConstraints(
                0,
                0,
                1,
                1,
                GridConstraints.ANCHOR_WEST,
                GridConstraints.FILL_HORIZONTAL,
                GridConstraints.SIZEPOLICY_CAN_GROW,
                GridConstraints.SIZEPOLICY_FIXED,
                null,
                new Dimension(50, 22),
                null,
                0,
                false
            )
        );
        final JLabel label2 = new JLabel();
        label2.setText(Strings.get(Strings.LABEL_PX));
        simpleBorderPanel.add(
            label2,
            new GridConstraints(
                0,
                1,
                1,
                1,
                GridConstraints.ANCHOR_WEST,
                GridConstraints.FILL_NONE,
                GridConstraints.SIZEPOLICY_FIXED,
                GridConstraints.SIZEPOLICY_FIXED,
                null,
                null,
                null,
                0,
                false
            )
        );
        expertBorderPanel = new JPanel();
        expertBorderPanel.setLayout(
            new GridLayoutManager(4, 3, new Insets(0, 0, 0, 0), -1, -1)
        );
        expertBorderPanel.setVisible(true);
        borderPanel.add(
            expertBorderPanel,
            new GridConstraints(
                0,
                2,
                1,
                1,
                GridConstraints.ANCHOR_CENTER,
                GridConstraints.FILL_BOTH,
                GridConstraints.SIZEPOLICY_CAN_SHRINK |
                GridConstraints.SIZEPOLICY_CAN_GROW,
                GridConstraints.SIZEPOLICY_CAN_SHRINK |
                GridConstraints.SIZEPOLICY_CAN_GROW,
                null,
                null,
                null,
                0,
                false
            )
        );
        final JLabel label3 = new JLabel();
        label3.setText(Strings.get(Strings.LABEL_BORDER_TOP));
        expertBorderPanel.add(
            label3,
            new GridConstraints(
                0,
                0,
                1,
                1,
                GridConstraints.ANCHOR_EAST,
                GridConstraints.FILL_NONE,
                GridConstraints.SIZEPOLICY_FIXED,
                GridConstraints.SIZEPOLICY_FIXED,
                null,
                null,
                null,
                0,
                false
            )
        );
        topSpinner = new JSpinner();
        expertBorderPanel.add(
            topSpinner,
            new GridConstraints(
                0,
                1,
                1,
                1,
                GridConstraints.ANCHOR_WEST,
                GridConstraints.FILL_HORIZONTAL,
                GridConstraints.SIZEPOLICY_CAN_GROW,
                GridConstraints.SIZEPOLICY_FIXED,
                null,
                new Dimension(50, 22),
                null,
                0,
                false
            )
        );
        final JLabel label4 = new JLabel();
        label4.setText(Strings.get(Strings.LABEL_BORDER_LEFT));
        expertBorderPanel.add(
            label4,
            new GridConstraints(
                1,
                0,
                1,
                1,
                GridConstraints.ANCHOR_EAST,
                GridConstraints.FILL_NONE,
                GridConstraints.SIZEPOLICY_FIXED,
                GridConstraints.SIZEPOLICY_FIXED,
                null,
                null,
                null,
                0,
                false
            )
        );
        leftSpinner = new JSpinner();
        expertBorderPanel.add(
            leftSpinner,
            new GridConstraints(
                1,
                1,
                1,
                1,
                GridConstraints.ANCHOR_WEST,
                GridConstraints.FILL_HORIZONTAL,
                GridConstraints.SIZEPOLICY_CAN_GROW,
                GridConstraints.SIZEPOLICY_FIXED,
                null,
                new Dimension(50, 22),
                null,
                0,
                false
            )
        );
        final JLabel label5 = new JLabel();
        label5.setText(Strings.get(Strings.LABEL_BORDER_BOTTOM));
        expertBorderPanel.add(
            label5,
            new GridConstraints(
                2,
                0,
                1,
                1,
                GridConstraints.ANCHOR_EAST,
                GridConstraints.FILL_NONE,
                GridConstraints.SIZEPOLICY_FIXED,
                GridConstraints.SIZEPOLICY_FIXED,
                null,
                null,
                null,
                0,
                false
            )
        );
        bottomSpinner = new JSpinner();
        expertBorderPanel.add(
            bottomSpinner,
            new GridConstraints(
                2,
                1,
                1,
                1,
                GridConstraints.ANCHOR_WEST,
                GridConstraints.FILL_HORIZONTAL,
                GridConstraints.SIZEPOLICY_CAN_GROW,
                GridConstraints.SIZEPOLICY_FIXED,
                null,
                new Dimension(50, 22),
                null,
                0,
                false
            )
        );
        final JLabel label6 = new JLabel();
        label6.setText(Strings.get(Strings.LABEL_BORDER_RIGHT));
        expertBorderPanel.add(
            label6,
            new GridConstraints(
                3,
                0,
                1,
                1,
                GridConstraints.ANCHOR_EAST,
                GridConstraints.FILL_NONE,
                GridConstraints.SIZEPOLICY_FIXED,
                GridConstraints.SIZEPOLICY_FIXED,
                null,
                null,
                null,
                0,
                false
            )
        );
        rightSpinner = new JSpinner();
        expertBorderPanel.add(
            rightSpinner,
            new GridConstraints(
                3,
                1,
                1,
                1,
                GridConstraints.ANCHOR_WEST,
                GridConstraints.FILL_HORIZONTAL,
                GridConstraints.SIZEPOLICY_CAN_GROW,
                GridConstraints.SIZEPOLICY_FIXED,
                null,
                new Dimension(50, 22),
                null,
                0,
                false
            )
        );
        final JLabel label7 = new JLabel();
        label7.setText(Strings.get(Strings.LABEL_PX));
        expertBorderPanel.add(
            label7,
            new GridConstraints(
                0,
                2,
                1,
                1,
                GridConstraints.ANCHOR_WEST,
                GridConstraints.FILL_NONE,
                GridConstraints.SIZEPOLICY_FIXED,
                GridConstraints.SIZEPOLICY_FIXED,
                null,
                null,
                null,
                0,
                false
            )
        );
        final JLabel label8 = new JLabel();
        label8.setText(Strings.get(Strings.LABEL_PX));
        expertBorderPanel.add(
            label8,
            new GridConstraints(
                1,
                2,
                1,
                1,
                GridConstraints.ANCHOR_WEST,
                GridConstraints.FILL_NONE,
                GridConstraints.SIZEPOLICY_FIXED,
                GridConstraints.SIZEPOLICY_FIXED,
                null,
                null,
                null,
                0,
                false
            )
        );
        final JLabel label9 = new JLabel();
        label9.setText(Strings.get(Strings.LABEL_PX));
        expertBorderPanel.add(
            label9,
            new GridConstraints(
                2,
                2,
                1,
                1,
                GridConstraints.ANCHOR_WEST,
                GridConstraints.FILL_NONE,
                GridConstraints.SIZEPOLICY_FIXED,
                GridConstraints.SIZEPOLICY_FIXED,
                null,
                null,
                null,
                0,
                false
            )
        );
        final JLabel label10 = new JLabel();
        label10.setText(Strings.get(Strings.LABEL_PX));
        expertBorderPanel.add(
            label10,
            new GridConstraints(
                3,
                2,
                1,
                1,
                GridConstraints.ANCHOR_WEST,
                GridConstraints.FILL_NONE,
                GridConstraints.SIZEPOLICY_FIXED,
                GridConstraints.SIZEPOLICY_FIXED,
                null,
                null,
                null,
                0,
                false
            )
        );
        expertBorderButton = new JButton();
        expertBorderButton.setText(Strings.get(Strings.LABEL_BORDER_EXPERT));
        borderPanel.add(
            expertBorderButton,
            new GridConstraints(
                0,
                3,
                1,
                1,
                GridConstraints.ANCHOR_CENTER,
                GridConstraints.FILL_HORIZONTAL,
                GridConstraints.SIZEPOLICY_CAN_SHRINK |
                GridConstraints.SIZEPOLICY_CAN_GROW,
                GridConstraints.SIZEPOLICY_FIXED,
                null,
                null,
                null,
                0,
                false
            )
        );
        final Spacer spacer1 = new Spacer();
        borderPanel.add(
            spacer1,
            new GridConstraints(
                0,
                4,
                1,
                1,
                GridConstraints.ANCHOR_CENTER,
                GridConstraints.FILL_HORIZONTAL,
                GridConstraints.SIZEPOLICY_WANT_GROW,
                1,
                null,
                null,
                null,
                0,
                false
            )
        );
        final Spacer spacer2 = new Spacer();
        borderPanel.add(
            spacer2,
            new GridConstraints(
                1,
                2,
                1,
                1,
                GridConstraints.ANCHOR_CENTER,
                GridConstraints.FILL_VERTICAL,
                1,
                GridConstraints.SIZEPOLICY_WANT_GROW,
                null,
                null,
                null,
                0,
                false
            )
        );
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return borderPanel;
    }
}
