# suppress inspection "UnusedProperty" for whole file
@borderColor = #c0c0c0

# The default size is 13, which is too small for Source Sans 3
defaultFont = 14
[win]defaultFont = +2

# Tweak OptionPane spacing
OptionPane.buttonPadding = 13
OptionPane.border = 13,13,13,13
OptionPane.iconMessageGap = 13
OptionPane.maxCharactersPerLine = 50

# Tweak insets for text components
TextField.margin = 2,4,2,4
TextArea.margin = 2,5,2,5

TitlePane.foreground = #000000

ToggleButton.toolbar.selectedBackground = #8bcdff
ToggleButton.toolbar.disabledSelectedBackground = lighten($ToggleButton.toolbar.selectedBackground,13%)
ToggleButton.toolbar.hoverBackground = #e6e6e6

ToolBar.background = #f5f5f5
ToolBar.separatorColor = @borderColor

# Don't highlight toolbar button groups on hover
ToolBar.hoverButtonGroupBackground =
