# suppress inspection "UnusedProperty" for whole file
@borderColor = #c0c0c0
[dark]@borderColor = #505050

@baseBackground = #f5f5f5
[dark]@baseBackground = #2d2d30

@darkTextBackground = #242427

# The default size is 13, which is too small for Source Sans 3
defaultFont = 14
[win]defaultFont = +2

# The default dark panel is too dark
[dark]Panel.background = @baseBackground

# Tweak OptionPane spacing
OptionPane.buttonPadding = 13
OptionPane.border = 13,13,13,13
OptionPane.messageAreaBorder = 0,0,0,10
OptionPane.iconMessageGap = 13
OptionPane.maxCharactersPerLine = 50

# Tweak insets for text components
TextField.margin = 2,4,2,4
TextArea.margin = 2,5,2,5
[dark]TextField.background = @darkTextBackground
[dark]TextArea.background = @darkTextBackground
[dark]FormattedTextField.background = @darkTextBackground
[dark]PasswordField.background = @darkTextBackground
[dark]ComboBox.background = @darkTextBackground
[dark]Spinner.background = @darkTextBackground

ToggleButton.toolbar.selectedBackground = #8bcdff
[dark]ToggleButton.toolbar.selectedBackground = #2a5a8a
ToggleButton.toolbar.disabledSelectedBackground = lighten($ToggleButton.toolbar.selectedBackground,13%)
ToggleButton.toolbar.hoverBackground = #e6e6e6
[dark]ToggleButton.toolbar.hoverBackground = #4a4a4a

ToolBar.background = @baseBackground
[dark]ToolBar.background = @baseBackground
ToolBar.separatorColor = @borderColor

# Don't highlight toolbar button groups on hover
ToolBar.hoverButtonGroupBackground =

[dark]SplitPane.background = @baseBackground

# Custom keys for score surround areas
SongScribe.scorePanel.background = #c0c0c0
[dark]SongScribe.scorePanel.background = #1c1c1f
